os: linux
dist:trusty
sudo: true
language: android
android:
  components:
    - build-tools-28.0.3

addons:
  apt_packages:
    - pandoc
before_install:
  - source .ci_tools/before_install.sh
install:
  - source .ci_tools/install_dep.sh
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  # scripts excutes inside our repo directory on CI machine
  - export SAMPLE_CI_RESULT=0
  - source .ci_tools/setup_env.sh
  - source .ci_tools/build_samples.sh
  - source .ci_tools/run_samples.sh
  - source .ci_tools/misc_ci.sh
  - eval "[[ $SAMPLE_CI_RESULT == 0 ]]"
