name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build samples
      uses: github/codeql-action/init@v1
      with:
        languages: cpp
    - run: |
        pushd samples
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
    - name: Perform CodeQL Analysis on samples
      uses: github/codeql-action/analyze@v1
    - name: build OboeTester
      uses: github/codeql-action/init@v1
      with:
        languages: cpp
    - run: |
        pushd apps/OboeTester
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd
    - name: Perform CodeQL Analysis on OboeTester
      uses: github/codeql-action/analyze@v1
    - name: build fxlab
      run: |
        pushd apps/fxlab
        chmod +x gradlew
        ./gradlew -q clean bundleDebug
        popd